export const GET_TITLE_SEARCH = "SEARCH/GET_TITLE_SEARCH" as const;
export const GET_TITLE_SEARCH_SUCCESS = "SEARCH/GET_TITLE_SEARCH_SUCCESS" as const;
export const GET_TITLE_SEARCH_FAILURE = "SEARCH/GET_TITLE_SEARCH_FAILURE" as const;
