export const GET_AUTO_COMPLETE = "SEARCH/GET_AUTO_COMPLETE" as const;
export const GET_AUTO_COMPLETE_SUCCESS = "SEARCH/GET_AUTO_COMPLETE_SUCCESS" as const;
export const GET_AUTO_COMPLETE_FAILURE = "SEARCH/GET_AUTO_COMPLETE_FAILURE" as const;
