export const POST_VIDEO_UPLOAD = "CAMERA/POST_VIDEO_UPLOAD" as const;
export const POST_VIDEO_UPLOAD_SUCCESS = "CAMERA/POST_VIDEO_UPLOAD_SUCCESS" as const;
export const POST_VIDEO_UPLOAD_FAILURE = "CAMERA/POST_VIDEO_UPLOAD_FAILURE" as const;
