export const GET_STACKED_QUESTION_LIST =
  "STACKED_QUESTION_LIST/GET_STACKED_QUESTION_LIST" as const;

export const POST_STACKED_QUESTION_LIST =
  "STACKED_QUESTION_LIST/POST_STACKED_QUESTION_LIST" as const;
