export const GET_VIDEO_ANSWER_LIST = "FEED/GET_VIDEO_ANSWER_LIST" as const;
export const GET_VIDEO_ANSWER_LIST_SUCCESS = "FEED/GET_VIDEO_ANSWER_LIST_SUCCESS" as const;
export const GET_VIDEO_ANSWER_LIST_FAILURE = "FEED/GET_VIDEO_ANSWER_LIST_FAILURE" as const;

