export const GET_VIDEO_URL = "CAMERA/GET_VIDEO_URL" as const;
export const GET_VIDEO_URL_SUCCESS = "CAMERA/GET_VIDEO_URL_SUCCESS" as const;
export const GET_VIDEO_URL_FAILURE = "CAMERA/GET_VIDEO_URL_FAILURE" as const;
