export const GET_TEXT_ANSWER_LIST = "TEXT_ANSWER/GET_TEXT_ANSWER" as const;
export const GET_TEXT_ANSWER_LIST_SUCCESS = `${GET_TEXT_ANSWER_LIST}_SUCCESS` as const;
export const GET_TEXT_ANSWER_LIST_FAILURE = `${GET_TEXT_ANSWER_LIST}_FAILURE` as const;

export const POST_TEXT_ANSWER = "TEXT_ANSWER/POST_TEXT_ANSWER" as const;
export const POST_TEXT_ANSWER_SUCCESS = `${POST_TEXT_ANSWER}_SUCCESS` as const;
export const POST_TEXT_ANSWER_FAILURE = `${POST_TEXT_ANSWER}_FAILURE` as const;

export const DELETE_TEXT_ANSWER = "TEXT_ANSWER/DELETE_TEXT_ANSWER" as const;
export const DELETE_TEXT_ANSWER_SUCCESS = `${DELETE_TEXT_ANSWER}_SUCCESS` as const;
export const DELETE_TEXT_ANSWER_FAILURE = `${DELETE_TEXT_ANSWER}_FAILURE` as const;
