export const POST_QUESTION_VIDEO_DATA = "CAMERA/POST_QUESTION_VIDEO_DATA" as const;
export const POST_QUESTION_VIDEO_DATA_SUCCESS = "CAMERA/POST_QUESTION_VIDEO_DATA_SUCCESS" as const;
export const POST_QUESTION_VIDEO_DATA_FAILURE = "CAMERA/POST_QUESTION_VIDEO_DATA_FAILURE" as const;
export const POST_ANSWER_VIDEO_DATA = "CAMERA/POST_ANSWER_VIDEO_DATA" as const;
export const POST_ANSWER_VIDEO_DATA_SUCCESS = "CAMERA/POST_ANSWER_VIDEO_DATA_SUCCESS" as const;
export const POST_ANSWER_VIDEO_DATA_FAILURE = "CAMERA/POST_ANSWER_VIDEO_DATA_FAILURE" as const;
