export const GET_QUESTION_LIST = "QUESTION/GET_QUESTION_LIST";
export const GET_QUESTION_LIST_SUCCESS = "QUESTION/GET_QUESTION_LIST_SUCCESS";
export const GET_QUESTION_LIST_FAILURE = "QUESTION/GET_QUESTION_LIST_FAILURE";

export const DELETE_QUESTION = "QUESTION/DELETE_QUESTION";
export const DELETE_QUESTION_SUCCESS = "QUESTION/DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAILURE = "QUESTION/DELETE_QUESTION_FAILURE";