export const GET_PROFILE = "PROFILE/GET_PROFILE" as const;
export const GET_PROFILE_FAILURE = `${GET_PROFILE}_FAILURE` as const;
export const GET_PROFILE_SUCCESS = `${GET_PROFILE}_SUCCESS` as const;
export const GET_PROFILE_QUESTION_LIST =
  "PROFILE/GET_PROFILE_QUESTION_LIST" as const;
export const GET_PROFILE_QUESTION_LIST_FAILURE =
  `${GET_PROFILE_QUESTION_LIST}_FAILURE` as const;
export const GET_PROFILE_QUESTION_LIST_SUCCESS =
  `${GET_PROFILE_QUESTION_LIST}_SUCCESS` as const;
export const SET_ID = "PROFILE/SET_ID" as const;
