enum uri {
  videoAnswer = "/answer/video",
  videoAnswerDetail = "/answer/video/detail",
  videoAnswerAdoption = "/answer/video/adoption",
  textAnswerAdoption = "/answer/adoption",
  commentAnswer = "/answer/text",
  googleSignin = "/google",
  like = "/like",
  file = "/video/file",
  getProfile = "/user/info/",
  myId = "/user/my",
  auto_complete = "/search/autocomplete",
  question = "/question",
  stack_question = "/question/video",
  answer = "/answer/video/",
  title = "/search/title",
  getProfileQuestionList = "/user/question/video/",
  signin = "/auth?provider=",
  reportVideo = "/admin/report/video",
  reportComment = "/admin/report/comment",
  appleSignin = "/apple",
  interests = "/interests",
}

export default uri;
